### PR TITLE
Allow comments in download_scripts

### PR DESCRIPTION
**Pull request by scop**
For example TODOs.

### CODE REVIEW

**Comment by asottile** [comment]
I would rather instead declare comments unsupported

**Comment by scop** [comment]
Hm, curious, what downsides do you see with supporting them?

**Comment by scop** [comment]
If one wants to place comments, now they need to reside away from context, in the "regular cfg area", making them harder to find and pinpoint the thing they address.

**Comment by asottile** [comment]
afaict this isn't needed at all -- comments are already stripped via setuptools it's only "inline" comments which aren't allowed (and aren't part of ini spec anyway)

this test already passes:

```diff
$ git diff
diff --git a/tests/setuptools_download_test.py b/tests/setuptools_download_test.py
index 3872a6e..654092d 100644
--- a/tests/setuptools_download_test.py
+++ b/tests/setuptools_download_test.py
@@ -416,9 +416,13 @@ def test_integration_data_file(file_server, tmp_path):
     setup_cfg = f'''\
 [setuptools_download]
 download_data_files =
+    # wat4
     [share/example/f]
+    # wat
     url = {file_server.host}/plain
+    # wat 2
     sha256 = {file_server.plain_sha256}
+    # wat3
 '''
     tmp_path.joinpath('setup.cfg').write_text(setup_cfg)
     tmp_path.joinpath('setup.py').write_text(_SETUP_PY)
```

**Comment by scop** [comment]
Yah, I suppose comments alone on a line is good enough. Did not know that trailing ones are not in ini specs.

**Pull request closed without merging**
